# This rule is not used by the project keystone-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over keystone.openstack.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keystone-operator
    app.kubernetes.io/managed-by: kustomize
  name: keystoneendpoint-admin-role
rules:
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  verbs:
  - '*'
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints/status
  verbs:
  - get
