apiVersion: keystone.openstack.org/v1
kind: KeystoneAPI
metadata:
  name: keystone
spec:
  adminPassword: foobar123
  containerImage: docker.io/tripleotrain/centos-binary-keystone:current-tripleo
  replicas: 1
  databasePassword: foobar123
  databaseHostname: openstack-db-mariadb
  # used to create the DB schema
  databaseAdminUsername: root
  databaseAdminPassword: foobar123
  mysqlContainerImage: docker.io/tripleomaster/centos-binary-mariadb:current-tripleo
