apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: keystoneapis.keystone.openstack.org
spec:
  group: keystone.openstack.org
  names:
    kind: KeystoneAPI
    listKind: KeystoneAPIList
    plural: keystoneapis
    singular: keystoneapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: KeystoneAPI is the Schema for the keystoneapis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: KeystoneAPISpec defines the desired state of KeystoneAPI
          properties:
            adminPassword:
              description: Keystone API Admin Password
              type: string
            apiEndpoint:
              description: Keystone API Endpoint, the http/https route configured
                to access the Keystone API
              type: string
            containerImage:
              description: Keystone Container Image URL
              type: string
            databaseAdminPassword:
              description: Database Admin Password
              type: string
            databaseAdminUsername:
              description: Database Admin Username
              type: string
            databaseHostname:
              description: Keystone Database Hostname String
              type: string
            databasePassword:
              description: Keystone Database Password String
              type: string
            mysqlContainerImage:
              description: Mysql Container Image URL (used for database syncing)
              type: string
            replicas:
              description: Replicas
              format: int32
              type: integer
          required:
          - replicas
          type: object
        status:
          description: KeystoneAPIStatus defines the observed state of KeystoneAPI
          properties:
            bootstrapHash:
              description: bootstrap completed
              type: string
            dbSyncHash:
              description: Deployment messages Messages []string `json:"messages,omitempty"`
                DbSync hash
              type: string
            deploymentHash:
              description: Deployment hash used to detect changes
              type: string
          required:
          - bootstrapHash
          - dbSyncHash
          - deploymentHash
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
